# Generated by Django 5.2.10 on 2026-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'Registration Desk Officer')], default='STAFF', max_length=20),
        ),
    ]
