# Generated by Django 5.2.10 on 2026-01-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('CORE', 'Core Department'), ('SUPPORT', 'Support Service')], default='CORE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
