# Generated by Django 5.2.10 on 2026-01-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_department_category_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('CONTRACTOR', 'Contractor'), ('GOV_OFFICIAL', 'Government Official'), ('VISITOR', 'Visitor')], default='VISITOR', max_length=50),
        ),
    ]
