# Generated by Django 5.2.11 on 2026-02-26 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['check_in_time'], name='visitors_vi_check_i_436612_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['checked_out'], name='visitors_vi_checked_72f90f_idx'),
        ),
    ]
