# Generated by Django 5.2.11 on 2026-03-03 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_alter_visitor_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact must be 9-15 digits only', regex='^\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='ID number must contain digits only', regex='^\\d+$')]),
        ),
    ]
