# Generated by Django 5.2.11 on 2026-03-03 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_alter_visitor_contact_alter_visitor_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ID number must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
